name: Greet Everyone

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: pwd
      - name: path
        run: echo $PATH
      - name: brew
        run: brew list
