name: CI
"on":
  - push
jobs:
    aws-acm-cert:
        name: aws-acm-cert
        runs-on: ubuntu-latest
        timeout-minutes: 45
        steps:
          - run: env
          - uses: actions/checkout@v2
          - name: cache homebrew
            uses: actions/cache@v2
            with:
                key: ${{ runner.os }}-brew-${{ hashFiles('Brewfile.lock.json') }}
                path: /home/linuxbrew/.linuxbrew
          - run: brew bundle install
          - run: "\n                        cat << EOF > ~/.aws/credentials\n                        [cztack-ci-1]\n                        aws_access_key_id=${{ secrets.CI1_AWS_ACCESS_KEY_ID }}\n                        aws_secret_access_key=${{ secrets.CI1_AWS_SECRET_ACCESS_KEY }}\n\n                        [cztack-ci-2]\n                        aws_access_key_id=${{ secrets.CI2_AWS_ACCESS_KEY_ID }}\n                        aws_secret_access_key=${{ secrets.CI2_AWS_SECRET_ACCESS_KEY }}\n                        EOF\n\n                    "
          - run: aws --profile cztack-ci-1 sts get-caller-identity
          - run: aws --profile cztack-ci-2 sts get-caller-identity
